name: PPA Compilation
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  update-ppa:
    runs-on: ubuntu-latest
    steps:

      # Checkout the branch
    - name: checkout
      uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

    - name: Fetch latest releases
      id: fetch
      run: |
        chmod +x ./get-packages.sh
        ./get-packages.sh
        git add .
        CHANGES=`git diff --name-only HEAD`
        echo "::set-output name=ARCH::$(if [[ `echo ${CHNAGES}|grep "arch" | wc -l` > 0 ]]; then exit 0; else exit 1; fi)\n"
        echo "::set-output name=DEBIAN::$(if [[ `echo ${CHNAGES}|grep "debian" | wc -l` > 0 ]]; then exit 0; else exit 1; fi)\n"
        #if [[ `echo ${CHNAGES} | wc -l` > 0 ]]; then exit 0; else exit 1; fi
    - name: Configure GPG Key
      if: steps.fetch.outputs.DEBIAN == 0
      run: |
        echo -n "$PPA_KEY" | base64 --decode | gpg --import
      env:
        PPA_KEY: ${{ secrets.PPA_KEY }}

    - name: Update Debian PPA
      if: steps.fetch.outputs.DEBIAN == 0
      run: |
       cd debian
       chmod +x ./update.sh
       ./update.sh

    - name: Update Arch PPA
      if: steps.fetch.outputs.ARCH == 0
      run: |
       cd arch
       chmod +x ./update.sh
       ./update.sh

    - name: Update Website
      run: |
        ./update-docs.sh


    - name: commit
      continue-on-error: true
      run: |
       git config --global user.email "octokit@github.com"
       git config --global user.name "Github Actions"
       git add .
       git commit -m "ppa update"
       git push
       exit 0
